Update Site 2013/Entities/Company.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace update_site.Entities
{
    public class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Computer> Computers { get; set; } 
    }
}

Update Site 2013/Entities/Computer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace update_site.Entities
{
    public class Computer
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public string Model { get; set; }
        public List<Driver> Drivers { get; set; }
    }
}

Update Site 2013/Entities/Driver.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace update_site.Entities
{
    public class Driver
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Verstion { get; set; }
        public string Category { get; set; }
        public string FileLocation { get; set; }
    }
}

Update Site 2013/Entities/OS.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace update_site.Entities
{
    public class OS
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Update> Updates { get; set; } 
    }
}

Update Site 2013/Entities/Update.cs
namespace update_site.Entities
{
    public class Update
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Descripton { get; set; }
        public string OS { get; set; } // so I know what system this is for
        public bool Is32Bit { get; set; } // So I know if this update is for 32 or 64 bit OS's
        public int KBNumber { get; set; }
        public bool IsOptional { get; set; } // So I know if it's optional or important
        public string DownloadUrl { get; set; } // Public url
        public string FileLocation { get; set; } // My url
    }
}

Update Site 2013/Entities/Update2.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace update_site.Entities
{
    [Serializable]
    public class Update2
    {
        public Update2()
        {
            
        }

        public string Title { get; set; }
        public int KB { get; set; }
        public string Description {  get;  set; }
    }
}

Update Site 2013/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using update_site.repo;

namespace update_site.Controllers
{
    public abstract class BaseController : Controller
    {
        public SiteRepository  Repo = new SiteRepository();
    }
}

Update Site 2013/Controllers/DriversController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using update_site.Entities;

namespace update_site.Controllers
{
    public class DriversController : BaseController
    {
        //
        // GET: /Drivers/



        public ActionResult Index()
        {
            return View(Repo.GetCompanyList());
        }

        public ActionResult Computers(string companyName)
        {
            var company = Repo.GetCompanyList().First(x => x.Name == companyName);
            return View(company);
        }

    }
}

Update Site 2013/Controllers/HomeController.cs
using System.Web.Mvc;

namespace update_site.Controllers
{
    public class HomeController : BaseController
    {
        //
        // GET: /Index/

        public ActionResult Index()
        {
            //var repo = new SiteRepository();
            //repo.CreateOrRecreateDB();
            //repo.AddOs(new OS { Name = "Windows 98SE", Updates = new List<Update>() });
            //repo.AddOs(new OS { Name = "Windows XP", Updates = new List<Update>() });
            //repo.AddOs(new OS { Name = "Windows Vista", Updates = new List<Update>() });
            //repo.AddOs(new OS { Name = "Windows 7", Updates = new List<Update>() });
            //repo.SaveChanges();
            return View();
        }
    }
}

Update Site 2013/Controllers/WindowsUpdatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using update_site.Entities;
using update_site.repo;

namespace update_site.Controllers
{
    public class WindowsUpdatesController : BaseController
    {
        //
        // GET: /WindowsUpdates/

        public ActionResult Index()
        {
            
            return View(Repo.GetOsList());
        }

        public ActionResult UpdatesList(string os)
        {
            ViewBag.Title = "Updates for " + os;
            var updates = Repo.GetOs(os).Updates;
            return View(updates ?? new List<Update>());
        }

    }
}

Update Site 2013/Views/Drivers/Computers.cshtml
@model update_site.Entities.Company


<div class="Content">
<h3>@ViewBag.Title</h3>


@foreach (var computer in Model.Computers)
{
    <div class="computer">
        <img   src='@Url.Content(@"~/Images/Companies/"+computer.Company+"/Computers/"+computer.Model.Replace(" ","_")+".png")'  alt="Logo" onclick='location.href = "@Url.Action("Index")"'/> <br/>
        @computer.Model
   </div>
}

</div>

Update Site 2013/Views/Drivers/Index.cshtml
@model List<update_site.Entities.Company>

@{
    ViewBag.Title = "ComputerDrivers";
}

<h2>Computer Drivers</h2>


<div class="Content">


@foreach (var company in Model)
{

   <img class="company"  src='@Url.Content("~/Images/Companies/"+company.Name+"/logo.jpg")'  width="15%" height="15%" alt="Logo" onclick='location.href = "@Url.Action("Computers", new {companyName = company.Name})"'/>

}

</div>

Update Site 2013/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Driver Haven";
}

 <h2 style="width: 40%">Driver Haven</h2>

<div class="Content" style="margin: 20% auto; width:20%;">

    <img src="@Url.Content("~/Images/compuetr drivers.gif")" height="40%" width="40%" alt="Computer Drivers" style="margin-right: 5%"/>  <img src="@Url.Content("~/Images/windows logo.PNG")" width="40%" height="40%" alt="Windows Updates" /> <br/>
    <div style="margin-left: 7%; display:inline-block">@Html.ActionLink("Computer Drivers","Index","Drivers")  </div>                    <div style="margin-left: 13%; display: inline-block"> @Html.ActionLink("Windows Updates", "Index", "WindowsUpdates", new {Area = ""}, null) </div>
</div>

Update Site 2013/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Animate.css")" rel="stylesheet" type="text/css"/>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css"/>
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.6.2.js")" type="text/javascript"></script>
</head>

    <body>
        @RenderBody()
    
        <script type="text/javascript">

            $('.Content').addClass('animated fadeIn'); // fade me in jhony
        
            var Num = Math.floor(Math.random() * 7 + 1);
            var root = document.location.href;
            $('body').css({ 'background-image': 'url('+location.href.substring(0, location.href.indexOf('/'))+'/Images/Backgrounds/'+Num+'.jpg)' });

        
        </script>
    </body>
</html>

Update Site 2013/Views/WindowsUpdates/Index.cshtml
@model List<update_site.Entities.OS>

@{
    ViewBag.Title = "WindowsUpdates";
}

<h1>WindowsUpdates</h1>


<div class="Content">


@foreach (var os in Model)
{

   <img class="OS"  src='@Url.Content("~/Images/OS/"+os.Name+".jpg")'  width="45%" height="45%" alt="company Logo" onclick='location.href = "@Url.Action("UpdatesList",  new {os = @os.Name})"'/>

}

</div>

Update Site 2013/Views/WindowsUpdates/UpdatesList.cshtml
@model List<update_site.Entities.Update>


<div class="Content">
<h3>@ViewBag.Title</h3>
<table id="UpdateList" class="table">
        <tr>
            <th>KB</th>
            <th>Update Name</th>
            <th>Importance</th>
            <th>Description</th>
        </tr>

        @foreach (var update in Model)
        {
            <tr>
                <td><a href="@update.DownloadUrl">@update.KBNumber</a></td>
                <td>@update.Name</td>
                <td>@if(update.IsOptional)
                     {
                         <text>Optional</text>
                     }
                     else
                     {
                         <text>Important</text>
                     }
                </td>
                <td>@update.Descripton</td>
           </tr>
        }   

</table>
</div>